### ISSUE TITLE
Convoy with docker-compose fails nonexistent driver convoy

### ISSUE THREAD

**Issue by jonathan-kosgei** [rancher/convoy#207]
I have convoy running with:
```
/usr/local/bin/convoy -s "/var/run/convoy/convoy.sock" daemon --drivers ebs 2>> /var/log/convoy/stderr.log 1>> /var/log/convoy/stdout.log
```

I can create volumes from docker and convoy with:
```
convoy create test1
docker volume create --driver=convoy test2
```
They work.

But in trying to replicate the same with a compose file:
```
version: '3'
volumes:
  ebs:
    driver: convoy
    driver_opts:
      size: 5
services:
  mongo:
    image: mongo:3.4.3
    command: bash -c "mongod --replSet zipgo-rs0 --journal"
    ports:
      - "27017:27017"
    volumes:
      - ebs:/data
```

I get 
```
Creating volume "ubuntu_ebs" with convoy driver
ERROR: Volume ebs specifies nonexistent driver convoy
```
and `docker plugin ls` shows nothing
