### ISSUE TITLE
chown inside a convoy volume

### ISSUE THREAD

**Issue by oomathias** [rancher/convoy#79]
Hi!

I'm migrating all my volumes from local to convoy-nfs with rancher (all versions are latest).

Here is my docker-compose
```yml
gitlab-runner:
  image: sameersbn/gitlab-ci-multi-runner:1.0.4
  volumes:
    - gitlab_runner:/home/gitlab_ci_multi_runner/data
  volume-driver: convoy-nfs
```

The `entrypoint.sh` is doing a `chown` for whatever reason, which translate in `chown: changing ownership of '/home/gitlab_ci_multi_runner/data': Operation not permitted`, so the container never start.

Is this a normal behavior (chown not supported)?
